site_name: Taichi TopOpt

theme:
    name: readthedocs

markdown_extensions:
  - admonition

nav:
- Home: 'index.md'
- Roadmap: 'roadmap.md'
- APIs:
  - 'APIs': 'api/api.md'
  - 'Node Class': 'api/node.md'
  - 'Element Class': 'api/element.md'
- Examples:
  - 'Example': 'examples/example.md'

